# Generated by Django 6.0.4 on 2026-04-30 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_notification_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('gmail_email', models.EmailField(blank=True, default='', max_length=254)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
