# Generated by Django 6.0.4 on 2026-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_contact_email_job_contact_person_job_follow_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicant_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='applicant_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='email_consent',
            field=models.BooleanField(default=False),
        ),
    ]
